# Alacritty Configuration (TOML format)
# ~/.config/alacritty/alacritty.toml

shell = { program = "/usr/bin/zsh", args = ["-l"] }

# Общие настройки окна
[window]
opacity = 0.6
dynamic_padding = true
decorations = "Full"
startup_mode = "Windowed"
title = "Alacritty"

[window.padding]
x = 10
y = 10

[window.class]
instance = "Alacritty"
general = "Alacritty"

# Настройки скроллинга
[scrolling]
history = 10000
multiplier = 3

# Шрифт
[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 0
y = 0

# Цветовая схема Tokyo Night
[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.cursor]
text = "#1a1b26"
cursor = "#c0caf5"

[colors.selection]
text = "CellForeground"
background = "#33467c"

[colors.normal]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

# Настройки курсора
[cursor]
unfocused_hollow = true
blink_interval = 750

[cursor.style]
shape = "Block"
blinking = "On"

# Настройки колокольчика
[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

# Настройки мыши
[mouse]
hide_when_typing = true

# Привязки клавиш
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
action = "ScrollToBottom"
